
services:

  mysql_usuarios:
    image: mysql:8
    container_name: mysql_usuarios
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usuarios
      MYSQL_DATABASE: usuarios_db
      MYSQL_PASSWORD: root 
    ports:
      - "3307:3306"
    volumes:
      - mysql_usuarios_data:/var/lib/mysql

  mysql_plazoleta:
    image: mysql:8
    container_name: mysql_plazoleta
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plazoleta_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_plazoleta_data:/var/lib/mysql

volumes:
  mysql_usuarios_data:
  mysql_plazoleta_data:
